pipeline {

  agent any
  environment {
    //adding a comment for the commit test
    DEPLOY_CREDS = credentials('deploy-anypoint-user')
    MULE_VERSION = '4.2.2'
    BG = "MZA"
    WORKER = "MICRO"
  }
  stages {
    stage('Build') {
      steps {
            bat 'mvn -B -U -e -V clean -DskipTests package'
      }
    }

    stage('Test') {
      steps {
          bat "mvn test"
      }
    }

     stage('Deploy Development') {
      environment {
        ENVIRONMENT = 'Sandbox'
        APP_NAME = 'mule-hello-world-app'
      }
      steps {
            bat 'mvn -U -V -e -B -DskipTests deploy -DmuleDeploy -Dmule.version="4.2.2" -Danypoint.username="MZAM4B7" -Danypoint.password="Raz10zaq" -Dcloudhub.app="mule-hello-world-app" -Dcloudhub.environment="Sandbox" -Dcloudhub.bg="MZA" -Dcloudhub.worker="MICRO" -Denv="dev" -Danypoint.platform.client_id="bf449046d08f4001a38589662ae64b28" -Danypoint.platform.client_secret="69F8185524884512a9C8026D6E846142" -Danypoint.platform.base_uri="https://anypoint.mulesoft.com" -Danypoint.platform.analytics_base_uri="https://analytics-ingest.anypoint.mulesoft.com"'
      }
    }
  }

  tools {
    maven 'M3'
  }
}